//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.60818.0
// 
namespace NGTweet.ViewModels.INGTweetAuthenticationService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginRequest", Namespace="http://schemas.datacontract.org/2004/07/TweetSharpService.DTO")]
    public partial class LoginRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string PinField;
        
        private NGTweet.ViewModels.INGTweetAuthenticationService.OAuthRequestToken RequestTokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pin {
            get {
                return this.PinField;
            }
            set {
                if ((object.ReferenceEquals(this.PinField, value) != true)) {
                    this.PinField = value;
                    this.RaisePropertyChanged("Pin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NGTweet.ViewModels.INGTweetAuthenticationService.OAuthRequestToken RequestToken {
            get {
                return this.RequestTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestTokenField, value) != true)) {
                    this.RequestTokenField = value;
                    this.RaisePropertyChanged("RequestToken");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OAuthRequestToken", Namespace="http://schemas.datacontract.org/2004/07/TweetSharp")]
    public partial class OAuthRequestToken : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool OAuthCallbackConfirmedField;
        
        private string TokenField;
        
        private string TokenSecretField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OAuthCallbackConfirmed {
            get {
                return this.OAuthCallbackConfirmedField;
            }
            set {
                if ((this.OAuthCallbackConfirmedField.Equals(value) != true)) {
                    this.OAuthCallbackConfirmedField = value;
                    this.RaisePropertyChanged("OAuthCallbackConfirmed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenSecret {
            get {
                return this.TokenSecretField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenSecretField, value) != true)) {
                    this.TokenSecretField = value;
                    this.RaisePropertyChanged("TokenSecret");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResponse", Namespace="http://schemas.datacontract.org/2004/07/TweetSharpService.DTO")]
    public partial class LoginResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private NGTweet.ViewModels.INGTweetAuthenticationService.OAuthAccessToken OAuthAccessTokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NGTweet.ViewModels.INGTweetAuthenticationService.OAuthAccessToken OAuthAccessToken {
            get {
                return this.OAuthAccessTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.OAuthAccessTokenField, value) != true)) {
                    this.OAuthAccessTokenField = value;
                    this.RaisePropertyChanged("OAuthAccessToken");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OAuthAccessToken", Namespace="http://schemas.datacontract.org/2004/07/TweetSharp")]
    public partial class OAuthAccessToken : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ScreenNameField;
        
        private string TokenField;
        
        private string TokenSecretField;
        
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ScreenName {
            get {
                return this.ScreenNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ScreenNameField, value) != true)) {
                    this.ScreenNameField = value;
                    this.RaisePropertyChanged("ScreenName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenSecret {
            get {
                return this.TokenSecretField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenSecretField, value) != true)) {
                    this.TokenSecretField = value;
                    this.RaisePropertyChanged("TokenSecret");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRequestTokenResponse", Namespace="http://schemas.datacontract.org/2004/07/TweetSharpService.DTO")]
    public partial class GetRequestTokenResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Uri AuthorizationUriField;
        
        private NGTweet.ViewModels.INGTweetAuthenticationService.OAuthRequestToken RequestTokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Uri AuthorizationUri {
            get {
                return this.AuthorizationUriField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorizationUriField, value) != true)) {
                    this.AuthorizationUriField = value;
                    this.RaisePropertyChanged("AuthorizationUri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NGTweet.ViewModels.INGTweetAuthenticationService.OAuthRequestToken RequestToken {
            get {
                return this.RequestTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestTokenField, value) != true)) {
                    this.RequestTokenField = value;
                    this.RaisePropertyChanged("RequestToken");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetTweetResponse", Namespace="http://schemas.datacontract.org/2004/07/TweetSharpService.DTO")]
    public partial class GetTweetResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.ObjectModel.ObservableCollection<NGTweet.ViewModels.INGTweetAuthenticationService.NGTweeterStatus> TweeterStatusesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<NGTweet.ViewModels.INGTweetAuthenticationService.NGTweeterStatus> TweeterStatuses {
            get {
                return this.TweeterStatusesField;
            }
            set {
                if ((object.ReferenceEquals(this.TweeterStatusesField, value) != true)) {
                    this.TweeterStatusesField = value;
                    this.RaisePropertyChanged("TweeterStatuses");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NGTweeterStatus", Namespace="http://schemas.datacontract.org/2004/07/TweetSharpService.DomainObjects")]
    public partial class NGTweeterStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime CreatedDateField;
        
        private long IdField;
        
        private NGTweet.ViewModels.INGTweetAuthenticationService.NGTweeterStatus RetweetedStatusField;
        
        private string TweetField;
        
        private NGTweet.ViewModels.INGTweetAuthenticationService.NGTweeterUser UserField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NGTweet.ViewModels.INGTweetAuthenticationService.NGTweeterStatus RetweetedStatus {
            get {
                return this.RetweetedStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.RetweetedStatusField, value) != true)) {
                    this.RetweetedStatusField = value;
                    this.RaisePropertyChanged("RetweetedStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tweet {
            get {
                return this.TweetField;
            }
            set {
                if ((object.ReferenceEquals(this.TweetField, value) != true)) {
                    this.TweetField = value;
                    this.RaisePropertyChanged("Tweet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NGTweet.ViewModels.INGTweetAuthenticationService.NGTweeterUser User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NGTweeterUser", Namespace="http://schemas.datacontract.org/2004/07/TweetSharpService.DomainObjects")]
    public partial class NGTweeterUser : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdField;
        
        private string NameField;
        
        private string ProfileImageUrlField;
        
        private string ScreenNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfileImageUrl {
            get {
                return this.ProfileImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileImageUrlField, value) != true)) {
                    this.ProfileImageUrlField = value;
                    this.RaisePropertyChanged("ProfileImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ScreenName {
            get {
                return this.ScreenNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ScreenNameField, value) != true)) {
                    this.ScreenNameField = value;
                    this.RaisePropertyChanged("ScreenName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetTweetsRequest", Namespace="http://schemas.datacontract.org/2004/07/TweetSharpService.DTO")]
    public partial class GetTweetsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private NGTweet.ViewModels.INGTweetAuthenticationService.OAuthAccessToken AccessTokenField;
        
        private long LastTweetIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NGTweet.ViewModels.INGTweetAuthenticationService.OAuthAccessToken AccessToken {
            get {
                return this.AccessTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessTokenField, value) != true)) {
                    this.AccessTokenField = value;
                    this.RaisePropertyChanged("AccessToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long LastTweetId {
            get {
                return this.LastTweetIdField;
            }
            set {
                if ((this.LastTweetIdField.Equals(value) != true)) {
                    this.LastTweetIdField = value;
                    this.RaisePropertyChanged("LastTweetId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendTweetRequest", Namespace="http://schemas.datacontract.org/2004/07/TweetSharpService.DTO")]
    public partial class SendTweetRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private NGTweet.ViewModels.INGTweetAuthenticationService.OAuthAccessToken AccessTokenField;
        
        private string StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NGTweet.ViewModels.INGTweetAuthenticationService.OAuthAccessToken AccessToken {
            get {
                return this.AccessTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessTokenField, value) != true)) {
                    this.AccessTokenField = value;
                    this.RaisePropertyChanged("AccessToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendTweetResponse", Namespace="http://schemas.datacontract.org/2004/07/TweetSharpService.DTO")]
    public partial class SendTweetResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private NGTweet.ViewModels.INGTweetAuthenticationService.NGTweeterStatus TweeterStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NGTweet.ViewModels.INGTweetAuthenticationService.NGTweeterStatus TweeterStatus {
            get {
                return this.TweeterStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.TweeterStatusField, value) != true)) {
                    this.TweeterStatusField = value;
                    this.RaisePropertyChanged("TweeterStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetweetRequest", Namespace="http://schemas.datacontract.org/2004/07/TweetSharpService.DTO")]
    public partial class RetweetRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private NGTweet.ViewModels.INGTweetAuthenticationService.OAuthAccessToken AccessTokenField;
        
        private long TweetIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NGTweet.ViewModels.INGTweetAuthenticationService.OAuthAccessToken AccessToken {
            get {
                return this.AccessTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessTokenField, value) != true)) {
                    this.AccessTokenField = value;
                    this.RaisePropertyChanged("AccessToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TweetId {
            get {
                return this.TweetIdField;
            }
            set {
                if ((this.TweetIdField.Equals(value) != true)) {
                    this.TweetIdField = value;
                    this.RaisePropertyChanged("TweetId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetweetResponse", Namespace="http://schemas.datacontract.org/2004/07/TweetSharpService.DTO")]
    public partial class RetweetResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private NGTweet.ViewModels.INGTweetAuthenticationService.NGTweeterStatus TweeterStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NGTweet.ViewModels.INGTweetAuthenticationService.NGTweeterStatus TweeterStatus {
            get {
                return this.TweeterStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.TweeterStatusField, value) != true)) {
                    this.TweeterStatusField = value;
                    this.RaisePropertyChanged("TweeterStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="INGTweetAuthenticationService.INGTweetAuthenticationService")]
    public interface INGTweetAuthenticationService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/INGTweetAuthenticationService/Login", ReplyAction="http://tempuri.org/INGTweetAuthenticationService/LoginResponse")]
        System.IAsyncResult BeginLogin(NGTweet.ViewModels.INGTweetAuthenticationService.LoginRequest request, System.AsyncCallback callback, object asyncState);
        
        NGTweet.ViewModels.INGTweetAuthenticationService.LoginResponse EndLogin(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/INGTweetAuthenticationService/GetRequestToken", ReplyAction="http://tempuri.org/INGTweetAuthenticationService/GetRequestTokenResponse")]
        System.IAsyncResult BeginGetRequestToken(System.AsyncCallback callback, object asyncState);
        
        NGTweet.ViewModels.INGTweetAuthenticationService.GetRequestTokenResponse EndGetRequestToken(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/INGTweetAuthenticationService/GetTweets", ReplyAction="http://tempuri.org/INGTweetAuthenticationService/GetTweetsResponse")]
        System.IAsyncResult BeginGetTweets(NGTweet.ViewModels.INGTweetAuthenticationService.OAuthAccessToken access, System.AsyncCallback callback, object asyncState);
        
        NGTweet.ViewModels.INGTweetAuthenticationService.GetTweetResponse EndGetTweets(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/INGTweetAuthenticationService/GetTweetsMentioningMe", ReplyAction="http://tempuri.org/INGTweetAuthenticationService/GetTweetsMentioningMeResponse")]
        System.IAsyncResult BeginGetTweetsMentioningMe(NGTweet.ViewModels.INGTweetAuthenticationService.OAuthAccessToken access, System.AsyncCallback callback, object asyncState);
        
        NGTweet.ViewModels.INGTweetAuthenticationService.GetTweetResponse EndGetTweetsMentioningMe(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/INGTweetAuthenticationService/GetTweetsSince", ReplyAction="http://tempuri.org/INGTweetAuthenticationService/GetTweetsSinceResponse")]
        System.IAsyncResult BeginGetTweetsSince(NGTweet.ViewModels.INGTweetAuthenticationService.GetTweetsRequest request, System.AsyncCallback callback, object asyncState);
        
        NGTweet.ViewModels.INGTweetAuthenticationService.GetTweetResponse EndGetTweetsSince(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/INGTweetAuthenticationService/SendTweet", ReplyAction="http://tempuri.org/INGTweetAuthenticationService/SendTweetResponse")]
        System.IAsyncResult BeginSendTweet(NGTweet.ViewModels.INGTweetAuthenticationService.SendTweetRequest request, System.AsyncCallback callback, object asyncState);
        
        NGTweet.ViewModels.INGTweetAuthenticationService.SendTweetResponse EndSendTweet(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/INGTweetAuthenticationService/Retweet", ReplyAction="http://tempuri.org/INGTweetAuthenticationService/RetweetResponse")]
        System.IAsyncResult BeginRetweet(NGTweet.ViewModels.INGTweetAuthenticationService.RetweetRequest request, System.AsyncCallback callback, object asyncState);
        
        NGTweet.ViewModels.INGTweetAuthenticationService.RetweetResponse EndRetweet(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INGTweetAuthenticationServiceChannel : NGTweet.ViewModels.INGTweetAuthenticationService.INGTweetAuthenticationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public NGTweet.ViewModels.INGTweetAuthenticationService.LoginResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((NGTweet.ViewModels.INGTweetAuthenticationService.LoginResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetRequestTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetRequestTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public NGTweet.ViewModels.INGTweetAuthenticationService.GetRequestTokenResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((NGTweet.ViewModels.INGTweetAuthenticationService.GetRequestTokenResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetTweetsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetTweetsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public NGTweet.ViewModels.INGTweetAuthenticationService.GetTweetResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((NGTweet.ViewModels.INGTweetAuthenticationService.GetTweetResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetTweetsMentioningMeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetTweetsMentioningMeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public NGTweet.ViewModels.INGTweetAuthenticationService.GetTweetResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((NGTweet.ViewModels.INGTweetAuthenticationService.GetTweetResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetTweetsSinceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetTweetsSinceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public NGTweet.ViewModels.INGTweetAuthenticationService.GetTweetResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((NGTweet.ViewModels.INGTweetAuthenticationService.GetTweetResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendTweetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SendTweetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public NGTweet.ViewModels.INGTweetAuthenticationService.SendTweetResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((NGTweet.ViewModels.INGTweetAuthenticationService.SendTweetResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetweetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RetweetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public NGTweet.ViewModels.INGTweetAuthenticationService.RetweetResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((NGTweet.ViewModels.INGTweetAuthenticationService.RetweetResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NGTweetAuthenticationServiceClient : System.ServiceModel.ClientBase<NGTweet.ViewModels.INGTweetAuthenticationService.INGTweetAuthenticationService>, NGTweet.ViewModels.INGTweetAuthenticationService.INGTweetAuthenticationService {
        
        private BeginOperationDelegate onBeginLoginDelegate;
        
        private EndOperationDelegate onEndLoginDelegate;
        
        private System.Threading.SendOrPostCallback onLoginCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetRequestTokenDelegate;
        
        private EndOperationDelegate onEndGetRequestTokenDelegate;
        
        private System.Threading.SendOrPostCallback onGetRequestTokenCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetTweetsDelegate;
        
        private EndOperationDelegate onEndGetTweetsDelegate;
        
        private System.Threading.SendOrPostCallback onGetTweetsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetTweetsMentioningMeDelegate;
        
        private EndOperationDelegate onEndGetTweetsMentioningMeDelegate;
        
        private System.Threading.SendOrPostCallback onGetTweetsMentioningMeCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetTweetsSinceDelegate;
        
        private EndOperationDelegate onEndGetTweetsSinceDelegate;
        
        private System.Threading.SendOrPostCallback onGetTweetsSinceCompletedDelegate;
        
        private BeginOperationDelegate onBeginSendTweetDelegate;
        
        private EndOperationDelegate onEndSendTweetDelegate;
        
        private System.Threading.SendOrPostCallback onSendTweetCompletedDelegate;
        
        private BeginOperationDelegate onBeginRetweetDelegate;
        
        private EndOperationDelegate onEndRetweetDelegate;
        
        private System.Threading.SendOrPostCallback onRetweetCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public NGTweetAuthenticationServiceClient() {
        }
        
        public NGTweetAuthenticationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NGTweetAuthenticationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NGTweetAuthenticationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NGTweetAuthenticationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<LoginCompletedEventArgs> LoginCompleted;
        
        public event System.EventHandler<GetRequestTokenCompletedEventArgs> GetRequestTokenCompleted;
        
        public event System.EventHandler<GetTweetsCompletedEventArgs> GetTweetsCompleted;
        
        public event System.EventHandler<GetTweetsMentioningMeCompletedEventArgs> GetTweetsMentioningMeCompleted;
        
        public event System.EventHandler<GetTweetsSinceCompletedEventArgs> GetTweetsSinceCompleted;
        
        public event System.EventHandler<SendTweetCompletedEventArgs> SendTweetCompleted;
        
        public event System.EventHandler<RetweetCompletedEventArgs> RetweetCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult NGTweet.ViewModels.INGTweetAuthenticationService.INGTweetAuthenticationService.BeginLogin(NGTweet.ViewModels.INGTweetAuthenticationService.LoginRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLogin(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NGTweet.ViewModels.INGTweetAuthenticationService.LoginResponse NGTweet.ViewModels.INGTweetAuthenticationService.INGTweetAuthenticationService.EndLogin(System.IAsyncResult result) {
            return base.Channel.EndLogin(result);
        }
        
        private System.IAsyncResult OnBeginLogin(object[] inValues, System.AsyncCallback callback, object asyncState) {
            NGTweet.ViewModels.INGTweetAuthenticationService.LoginRequest request = ((NGTweet.ViewModels.INGTweetAuthenticationService.LoginRequest)(inValues[0]));
            return ((NGTweet.ViewModels.INGTweetAuthenticationService.INGTweetAuthenticationService)(this)).BeginLogin(request, callback, asyncState);
        }
        
        private object[] OnEndLogin(System.IAsyncResult result) {
            NGTweet.ViewModels.INGTweetAuthenticationService.LoginResponse retVal = ((NGTweet.ViewModels.INGTweetAuthenticationService.INGTweetAuthenticationService)(this)).EndLogin(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLoginCompleted(object state) {
            if ((this.LoginCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoginCompleted(this, new LoginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoginAsync(NGTweet.ViewModels.INGTweetAuthenticationService.LoginRequest request) {
            this.LoginAsync(request, null);
        }
        
        public void LoginAsync(NGTweet.ViewModels.INGTweetAuthenticationService.LoginRequest request, object userState) {
            if ((this.onBeginLoginDelegate == null)) {
                this.onBeginLoginDelegate = new BeginOperationDelegate(this.OnBeginLogin);
            }
            if ((this.onEndLoginDelegate == null)) {
                this.onEndLoginDelegate = new EndOperationDelegate(this.OnEndLogin);
            }
            if ((this.onLoginCompletedDelegate == null)) {
                this.onLoginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoginCompleted);
            }
            base.InvokeAsync(this.onBeginLoginDelegate, new object[] {
                        request}, this.onEndLoginDelegate, this.onLoginCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult NGTweet.ViewModels.INGTweetAuthenticationService.INGTweetAuthenticationService.BeginGetRequestToken(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetRequestToken(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NGTweet.ViewModels.INGTweetAuthenticationService.GetRequestTokenResponse NGTweet.ViewModels.INGTweetAuthenticationService.INGTweetAuthenticationService.EndGetRequestToken(System.IAsyncResult result) {
            return base.Channel.EndGetRequestToken(result);
        }
        
        private System.IAsyncResult OnBeginGetRequestToken(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((NGTweet.ViewModels.INGTweetAuthenticationService.INGTweetAuthenticationService)(this)).BeginGetRequestToken(callback, asyncState);
        }
        
        private object[] OnEndGetRequestToken(System.IAsyncResult result) {
            NGTweet.ViewModels.INGTweetAuthenticationService.GetRequestTokenResponse retVal = ((NGTweet.ViewModels.INGTweetAuthenticationService.INGTweetAuthenticationService)(this)).EndGetRequestToken(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetRequestTokenCompleted(object state) {
            if ((this.GetRequestTokenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetRequestTokenCompleted(this, new GetRequestTokenCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetRequestTokenAsync() {
            this.GetRequestTokenAsync(null);
        }
        
        public void GetRequestTokenAsync(object userState) {
            if ((this.onBeginGetRequestTokenDelegate == null)) {
                this.onBeginGetRequestTokenDelegate = new BeginOperationDelegate(this.OnBeginGetRequestToken);
            }
            if ((this.onEndGetRequestTokenDelegate == null)) {
                this.onEndGetRequestTokenDelegate = new EndOperationDelegate(this.OnEndGetRequestToken);
            }
            if ((this.onGetRequestTokenCompletedDelegate == null)) {
                this.onGetRequestTokenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetRequestTokenCompleted);
            }
            base.InvokeAsync(this.onBeginGetRequestTokenDelegate, null, this.onEndGetRequestTokenDelegate, this.onGetRequestTokenCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult NGTweet.ViewModels.INGTweetAuthenticationService.INGTweetAuthenticationService.BeginGetTweets(NGTweet.ViewModels.INGTweetAuthenticationService.OAuthAccessToken access, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetTweets(access, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NGTweet.ViewModels.INGTweetAuthenticationService.GetTweetResponse NGTweet.ViewModels.INGTweetAuthenticationService.INGTweetAuthenticationService.EndGetTweets(System.IAsyncResult result) {
            return base.Channel.EndGetTweets(result);
        }
        
        private System.IAsyncResult OnBeginGetTweets(object[] inValues, System.AsyncCallback callback, object asyncState) {
            NGTweet.ViewModels.INGTweetAuthenticationService.OAuthAccessToken access = ((NGTweet.ViewModels.INGTweetAuthenticationService.OAuthAccessToken)(inValues[0]));
            return ((NGTweet.ViewModels.INGTweetAuthenticationService.INGTweetAuthenticationService)(this)).BeginGetTweets(access, callback, asyncState);
        }
        
        private object[] OnEndGetTweets(System.IAsyncResult result) {
            NGTweet.ViewModels.INGTweetAuthenticationService.GetTweetResponse retVal = ((NGTweet.ViewModels.INGTweetAuthenticationService.INGTweetAuthenticationService)(this)).EndGetTweets(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetTweetsCompleted(object state) {
            if ((this.GetTweetsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetTweetsCompleted(this, new GetTweetsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetTweetsAsync(NGTweet.ViewModels.INGTweetAuthenticationService.OAuthAccessToken access) {
            this.GetTweetsAsync(access, null);
        }
        
        public void GetTweetsAsync(NGTweet.ViewModels.INGTweetAuthenticationService.OAuthAccessToken access, object userState) {
            if ((this.onBeginGetTweetsDelegate == null)) {
                this.onBeginGetTweetsDelegate = new BeginOperationDelegate(this.OnBeginGetTweets);
            }
            if ((this.onEndGetTweetsDelegate == null)) {
                this.onEndGetTweetsDelegate = new EndOperationDelegate(this.OnEndGetTweets);
            }
            if ((this.onGetTweetsCompletedDelegate == null)) {
                this.onGetTweetsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTweetsCompleted);
            }
            base.InvokeAsync(this.onBeginGetTweetsDelegate, new object[] {
                        access}, this.onEndGetTweetsDelegate, this.onGetTweetsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult NGTweet.ViewModels.INGTweetAuthenticationService.INGTweetAuthenticationService.BeginGetTweetsMentioningMe(NGTweet.ViewModels.INGTweetAuthenticationService.OAuthAccessToken access, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetTweetsMentioningMe(access, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NGTweet.ViewModels.INGTweetAuthenticationService.GetTweetResponse NGTweet.ViewModels.INGTweetAuthenticationService.INGTweetAuthenticationService.EndGetTweetsMentioningMe(System.IAsyncResult result) {
            return base.Channel.EndGetTweetsMentioningMe(result);
        }
        
        private System.IAsyncResult OnBeginGetTweetsMentioningMe(object[] inValues, System.AsyncCallback callback, object asyncState) {
            NGTweet.ViewModels.INGTweetAuthenticationService.OAuthAccessToken access = ((NGTweet.ViewModels.INGTweetAuthenticationService.OAuthAccessToken)(inValues[0]));
            return ((NGTweet.ViewModels.INGTweetAuthenticationService.INGTweetAuthenticationService)(this)).BeginGetTweetsMentioningMe(access, callback, asyncState);
        }
        
        private object[] OnEndGetTweetsMentioningMe(System.IAsyncResult result) {
            NGTweet.ViewModels.INGTweetAuthenticationService.GetTweetResponse retVal = ((NGTweet.ViewModels.INGTweetAuthenticationService.INGTweetAuthenticationService)(this)).EndGetTweetsMentioningMe(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetTweetsMentioningMeCompleted(object state) {
            if ((this.GetTweetsMentioningMeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetTweetsMentioningMeCompleted(this, new GetTweetsMentioningMeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetTweetsMentioningMeAsync(NGTweet.ViewModels.INGTweetAuthenticationService.OAuthAccessToken access) {
            this.GetTweetsMentioningMeAsync(access, null);
        }
        
        public void GetTweetsMentioningMeAsync(NGTweet.ViewModels.INGTweetAuthenticationService.OAuthAccessToken access, object userState) {
            if ((this.onBeginGetTweetsMentioningMeDelegate == null)) {
                this.onBeginGetTweetsMentioningMeDelegate = new BeginOperationDelegate(this.OnBeginGetTweetsMentioningMe);
            }
            if ((this.onEndGetTweetsMentioningMeDelegate == null)) {
                this.onEndGetTweetsMentioningMeDelegate = new EndOperationDelegate(this.OnEndGetTweetsMentioningMe);
            }
            if ((this.onGetTweetsMentioningMeCompletedDelegate == null)) {
                this.onGetTweetsMentioningMeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTweetsMentioningMeCompleted);
            }
            base.InvokeAsync(this.onBeginGetTweetsMentioningMeDelegate, new object[] {
                        access}, this.onEndGetTweetsMentioningMeDelegate, this.onGetTweetsMentioningMeCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult NGTweet.ViewModels.INGTweetAuthenticationService.INGTweetAuthenticationService.BeginGetTweetsSince(NGTweet.ViewModels.INGTweetAuthenticationService.GetTweetsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetTweetsSince(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NGTweet.ViewModels.INGTweetAuthenticationService.GetTweetResponse NGTweet.ViewModels.INGTweetAuthenticationService.INGTweetAuthenticationService.EndGetTweetsSince(System.IAsyncResult result) {
            return base.Channel.EndGetTweetsSince(result);
        }
        
        private System.IAsyncResult OnBeginGetTweetsSince(object[] inValues, System.AsyncCallback callback, object asyncState) {
            NGTweet.ViewModels.INGTweetAuthenticationService.GetTweetsRequest request = ((NGTweet.ViewModels.INGTweetAuthenticationService.GetTweetsRequest)(inValues[0]));
            return ((NGTweet.ViewModels.INGTweetAuthenticationService.INGTweetAuthenticationService)(this)).BeginGetTweetsSince(request, callback, asyncState);
        }
        
        private object[] OnEndGetTweetsSince(System.IAsyncResult result) {
            NGTweet.ViewModels.INGTweetAuthenticationService.GetTweetResponse retVal = ((NGTweet.ViewModels.INGTweetAuthenticationService.INGTweetAuthenticationService)(this)).EndGetTweetsSince(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetTweetsSinceCompleted(object state) {
            if ((this.GetTweetsSinceCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetTweetsSinceCompleted(this, new GetTweetsSinceCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetTweetsSinceAsync(NGTweet.ViewModels.INGTweetAuthenticationService.GetTweetsRequest request) {
            this.GetTweetsSinceAsync(request, null);
        }
        
        public void GetTweetsSinceAsync(NGTweet.ViewModels.INGTweetAuthenticationService.GetTweetsRequest request, object userState) {
            if ((this.onBeginGetTweetsSinceDelegate == null)) {
                this.onBeginGetTweetsSinceDelegate = new BeginOperationDelegate(this.OnBeginGetTweetsSince);
            }
            if ((this.onEndGetTweetsSinceDelegate == null)) {
                this.onEndGetTweetsSinceDelegate = new EndOperationDelegate(this.OnEndGetTweetsSince);
            }
            if ((this.onGetTweetsSinceCompletedDelegate == null)) {
                this.onGetTweetsSinceCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTweetsSinceCompleted);
            }
            base.InvokeAsync(this.onBeginGetTweetsSinceDelegate, new object[] {
                        request}, this.onEndGetTweetsSinceDelegate, this.onGetTweetsSinceCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult NGTweet.ViewModels.INGTweetAuthenticationService.INGTweetAuthenticationService.BeginSendTweet(NGTweet.ViewModels.INGTweetAuthenticationService.SendTweetRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSendTweet(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NGTweet.ViewModels.INGTweetAuthenticationService.SendTweetResponse NGTweet.ViewModels.INGTweetAuthenticationService.INGTweetAuthenticationService.EndSendTweet(System.IAsyncResult result) {
            return base.Channel.EndSendTweet(result);
        }
        
        private System.IAsyncResult OnBeginSendTweet(object[] inValues, System.AsyncCallback callback, object asyncState) {
            NGTweet.ViewModels.INGTweetAuthenticationService.SendTweetRequest request = ((NGTweet.ViewModels.INGTweetAuthenticationService.SendTweetRequest)(inValues[0]));
            return ((NGTweet.ViewModels.INGTweetAuthenticationService.INGTweetAuthenticationService)(this)).BeginSendTweet(request, callback, asyncState);
        }
        
        private object[] OnEndSendTweet(System.IAsyncResult result) {
            NGTweet.ViewModels.INGTweetAuthenticationService.SendTweetResponse retVal = ((NGTweet.ViewModels.INGTweetAuthenticationService.INGTweetAuthenticationService)(this)).EndSendTweet(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSendTweetCompleted(object state) {
            if ((this.SendTweetCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SendTweetCompleted(this, new SendTweetCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SendTweetAsync(NGTweet.ViewModels.INGTweetAuthenticationService.SendTweetRequest request) {
            this.SendTweetAsync(request, null);
        }
        
        public void SendTweetAsync(NGTweet.ViewModels.INGTweetAuthenticationService.SendTweetRequest request, object userState) {
            if ((this.onBeginSendTweetDelegate == null)) {
                this.onBeginSendTweetDelegate = new BeginOperationDelegate(this.OnBeginSendTweet);
            }
            if ((this.onEndSendTweetDelegate == null)) {
                this.onEndSendTweetDelegate = new EndOperationDelegate(this.OnEndSendTweet);
            }
            if ((this.onSendTweetCompletedDelegate == null)) {
                this.onSendTweetCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSendTweetCompleted);
            }
            base.InvokeAsync(this.onBeginSendTweetDelegate, new object[] {
                        request}, this.onEndSendTweetDelegate, this.onSendTweetCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult NGTweet.ViewModels.INGTweetAuthenticationService.INGTweetAuthenticationService.BeginRetweet(NGTweet.ViewModels.INGTweetAuthenticationService.RetweetRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRetweet(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NGTweet.ViewModels.INGTweetAuthenticationService.RetweetResponse NGTweet.ViewModels.INGTweetAuthenticationService.INGTweetAuthenticationService.EndRetweet(System.IAsyncResult result) {
            return base.Channel.EndRetweet(result);
        }
        
        private System.IAsyncResult OnBeginRetweet(object[] inValues, System.AsyncCallback callback, object asyncState) {
            NGTweet.ViewModels.INGTweetAuthenticationService.RetweetRequest request = ((NGTweet.ViewModels.INGTweetAuthenticationService.RetweetRequest)(inValues[0]));
            return ((NGTweet.ViewModels.INGTweetAuthenticationService.INGTweetAuthenticationService)(this)).BeginRetweet(request, callback, asyncState);
        }
        
        private object[] OnEndRetweet(System.IAsyncResult result) {
            NGTweet.ViewModels.INGTweetAuthenticationService.RetweetResponse retVal = ((NGTweet.ViewModels.INGTweetAuthenticationService.INGTweetAuthenticationService)(this)).EndRetweet(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRetweetCompleted(object state) {
            if ((this.RetweetCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RetweetCompleted(this, new RetweetCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RetweetAsync(NGTweet.ViewModels.INGTweetAuthenticationService.RetweetRequest request) {
            this.RetweetAsync(request, null);
        }
        
        public void RetweetAsync(NGTweet.ViewModels.INGTweetAuthenticationService.RetweetRequest request, object userState) {
            if ((this.onBeginRetweetDelegate == null)) {
                this.onBeginRetweetDelegate = new BeginOperationDelegate(this.OnBeginRetweet);
            }
            if ((this.onEndRetweetDelegate == null)) {
                this.onEndRetweetDelegate = new EndOperationDelegate(this.OnEndRetweet);
            }
            if ((this.onRetweetCompletedDelegate == null)) {
                this.onRetweetCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRetweetCompleted);
            }
            base.InvokeAsync(this.onBeginRetweetDelegate, new object[] {
                        request}, this.onEndRetweetDelegate, this.onRetweetCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override NGTweet.ViewModels.INGTweetAuthenticationService.INGTweetAuthenticationService CreateChannel() {
            return new NGTweetAuthenticationServiceClientChannel(this);
        }
        
        private class NGTweetAuthenticationServiceClientChannel : ChannelBase<NGTweet.ViewModels.INGTweetAuthenticationService.INGTweetAuthenticationService>, NGTweet.ViewModels.INGTweetAuthenticationService.INGTweetAuthenticationService {
            
            public NGTweetAuthenticationServiceClientChannel(System.ServiceModel.ClientBase<NGTweet.ViewModels.INGTweetAuthenticationService.INGTweetAuthenticationService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginLogin(NGTweet.ViewModels.INGTweetAuthenticationService.LoginRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("Login", _args, callback, asyncState);
                return _result;
            }
            
            public NGTweet.ViewModels.INGTweetAuthenticationService.LoginResponse EndLogin(System.IAsyncResult result) {
                object[] _args = new object[0];
                NGTweet.ViewModels.INGTweetAuthenticationService.LoginResponse _result = ((NGTweet.ViewModels.INGTweetAuthenticationService.LoginResponse)(base.EndInvoke("Login", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetRequestToken(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetRequestToken", _args, callback, asyncState);
                return _result;
            }
            
            public NGTweet.ViewModels.INGTweetAuthenticationService.GetRequestTokenResponse EndGetRequestToken(System.IAsyncResult result) {
                object[] _args = new object[0];
                NGTweet.ViewModels.INGTweetAuthenticationService.GetRequestTokenResponse _result = ((NGTweet.ViewModels.INGTweetAuthenticationService.GetRequestTokenResponse)(base.EndInvoke("GetRequestToken", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetTweets(NGTweet.ViewModels.INGTweetAuthenticationService.OAuthAccessToken access, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = access;
                System.IAsyncResult _result = base.BeginInvoke("GetTweets", _args, callback, asyncState);
                return _result;
            }
            
            public NGTweet.ViewModels.INGTweetAuthenticationService.GetTweetResponse EndGetTweets(System.IAsyncResult result) {
                object[] _args = new object[0];
                NGTweet.ViewModels.INGTweetAuthenticationService.GetTweetResponse _result = ((NGTweet.ViewModels.INGTweetAuthenticationService.GetTweetResponse)(base.EndInvoke("GetTweets", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetTweetsMentioningMe(NGTweet.ViewModels.INGTweetAuthenticationService.OAuthAccessToken access, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = access;
                System.IAsyncResult _result = base.BeginInvoke("GetTweetsMentioningMe", _args, callback, asyncState);
                return _result;
            }
            
            public NGTweet.ViewModels.INGTweetAuthenticationService.GetTweetResponse EndGetTweetsMentioningMe(System.IAsyncResult result) {
                object[] _args = new object[0];
                NGTweet.ViewModels.INGTweetAuthenticationService.GetTweetResponse _result = ((NGTweet.ViewModels.INGTweetAuthenticationService.GetTweetResponse)(base.EndInvoke("GetTweetsMentioningMe", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetTweetsSince(NGTweet.ViewModels.INGTweetAuthenticationService.GetTweetsRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetTweetsSince", _args, callback, asyncState);
                return _result;
            }
            
            public NGTweet.ViewModels.INGTweetAuthenticationService.GetTweetResponse EndGetTweetsSince(System.IAsyncResult result) {
                object[] _args = new object[0];
                NGTweet.ViewModels.INGTweetAuthenticationService.GetTweetResponse _result = ((NGTweet.ViewModels.INGTweetAuthenticationService.GetTweetResponse)(base.EndInvoke("GetTweetsSince", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSendTweet(NGTweet.ViewModels.INGTweetAuthenticationService.SendTweetRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("SendTweet", _args, callback, asyncState);
                return _result;
            }
            
            public NGTweet.ViewModels.INGTweetAuthenticationService.SendTweetResponse EndSendTweet(System.IAsyncResult result) {
                object[] _args = new object[0];
                NGTweet.ViewModels.INGTweetAuthenticationService.SendTweetResponse _result = ((NGTweet.ViewModels.INGTweetAuthenticationService.SendTweetResponse)(base.EndInvoke("SendTweet", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRetweet(NGTweet.ViewModels.INGTweetAuthenticationService.RetweetRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("Retweet", _args, callback, asyncState);
                return _result;
            }
            
            public NGTweet.ViewModels.INGTweetAuthenticationService.RetweetResponse EndRetweet(System.IAsyncResult result) {
                object[] _args = new object[0];
                NGTweet.ViewModels.INGTweetAuthenticationService.RetweetResponse _result = ((NGTweet.ViewModels.INGTweetAuthenticationService.RetweetResponse)(base.EndInvoke("Retweet", _args, result)));
                return _result;
            }
        }
    }
}
